from _typeshed import Incomplete

def make_color(*args): ...
def reset(dispatch: bool = True) -> None: ...
def Screen(): ...

class _Screen:
    auto_repaint: bool
    def __init__(self) -> None: ...
    def clearscreen(self) -> None: ...
    clear = clearscreen
    def bgcolor(self, *args) -> None: ...
    def bgpic(self, *args) -> None: ...
    def resetscreen(self, *args) -> None: ...
    def screensize(self, *args) -> None: ...
    def setworldcoordinates(self, *args) -> None: ...
    def delay(self, duration: float): ...
    def update(self) -> None: ...
    def tracer(self, n: int = 0, delay: int = 0, hideturtle: bool = False) -> None: ...
    keydict: Incomplete
    def onkey(self, fun, key) -> None: ...
    onkeyrelease = onkey
    def onkeypress(self, fun, key) -> None: ...
    def listen(self) -> None: ...
    def ontimer(self, *args) -> None: ...
    def mainloop(self) -> None: ...
    def mode(self, mode=None): ...
    def colormode(self, *args) -> None: ...
    def getcanvas(self, *args) -> None: ...
    def getshapes(self, *args) -> None: ...
    def register_shape(self, *args) -> None: ...
    addshape = register_shape
    def turtles(self): ...
    def window_height(self, *args): ...
    def window_width(self, *args): ...
    def textinput(self, title: str, prompt: str = ''): ...
    def numinput(self, title: str, prompt: str = ''): ...
    def bye(self) -> None: ...
    def onclick(self, fun, btn: int = 1, add: bool = False) -> None: ...
    onscreenclick = onclick
    def ondrag(self, fun, btn: int = 1, add: bool = False) -> None: ...
    def exitonclick(self, *args) -> None: ...
    def setup(self, *args) -> None: ...
    def title(self, title) -> None: ...
    def onmove(self, fun, add: bool = False) -> None: ...
    def get_key(self): ...
    def get_key_wait(self): ...
    def is_key_pressed(self, key: str): ...
    def get_key_code(self): ...
    def get_key_code_wait(self): ...
    def is_key_code_pressed(self, key: int): ...

class Turtle:
    id: Incomplete
    def __init__(self, shape: str = None, undobuffersize: int = None, isvisible: bool = True) -> None: ...
    @classmethod
    def __resetTurtleClass__(cls) -> None: ...
    def clear(self, color=None) -> None: ...
    def clean(self, color=None) -> None: ...
    def forward(self, steps: float): ...
    fd = forward
    def backward(self, steps: float): ...
    back = backward
    bk = backward
    def right(self, deg: float): ...
    rt = right
    def left(self, deg: float): ...
    lt = left
    def setposition(self, x: float | tuple[float, float], y: float | None = None): ...
    setpos = setposition
    goto = setposition
    def teleport(self, x: float | tuple[float, float], y: float | None = None, fill_gap: bool | None = False): ...
    def setx(self, x: float): ...
    def sety(self, y: float): ...
    def setheading(self, deg: float): ...
    seth = setheading
    def home(self) -> None: ...
    def circle(self, radius: float, extent: float | None = None, steps: int | None = None): ...
    def dot(self, diameter=None) -> None: ...
    def stamp(self): ...
    def clearstamp(self, stamp_id: int): ...
    def clearstamps(self, stamp_ids: int | None = None): ...
    def undo(self, *args) -> None: ...
    def speed(self, newSpeed: float): ...
    def position(self): ...
    pos = position
    def towards(self, x: float | tuple[float, float], y: float | None = None): ...
    def xcor(self): ...
    def ycor(self): ...
    def heading(self): ...
    def distance(self, x: float | tuple[float, float], y: float | None = None): ...
    def degrees(self, fullcircle: int = 360) -> None: ...
    def radians(self) -> None: ...
    def pendown(self) -> None: ...
    pd = pendown
    down = pendown
    def penup(self) -> None: ...
    pu = penup
    up = penup
    def pensize(self, width: float): ...
    width = pensize
    def isdown(self): ...
    def color(self, *args): ...
    def pencolor(self, *args): ...
    def fillcolor(self, *args): ...
    def filling(self): ...
    def begin_fill(self) -> None: ...
    def end_fill(self) -> None: ...
    def write(self, text: str, move: bool = False, align: str = 'left', font=('arial', 8, 'normal')): ...
    def showturtle(self) -> None: ...
    st = showturtle
    def hideturtle(self) -> None: ...
    ht = hideturtle
    def isvisible(self): ...
    def shape(self, shape: str = None): ...
    def resizemode(self, rmode: str = None): ...
    def shapesize(self, *args) -> None: ...
    turtlesize = shapesize
    def shearfactor(self, *args) -> None: ...
    def settiltangle(self, *args) -> None: ...
    def tiltangle(self, *args) -> None: ...
    def tilt(self, *args) -> None: ...
    def shapetransform(self, *args) -> None: ...
    def get_shapepoly(self): ...
    def begin_poly(self, *args) -> None: ...
    def end_poly(self, *args) -> None: ...
    def get_poly(self, *args) -> None: ...
    def clone(self, *args) -> None: ...
    def getturtle(self, *args) -> None: ...
    getpen = getturtle
    def getscreen(self, *args) -> None: ...
    def setundobuffer(self, *args) -> None: ...
    def undobufferentries(self, *args) -> None: ...
    onclick: Incomplete
    ondrag: Incomplete
    onmove: Incomplete
    def get_pixel_color(self): ...
    def get_pixel_color_str(self): ...
Pen = Turtle

def get_event_log(blocking: bool = True): ...
def set_event_mode(state: bool): ...
def update_func(funcstr: str, fun, add: bool = False): ...

class Shape:
    def __init__(self, type_, data=None) -> None: ...
    def addcomponent(self, poly, fill, outline=None) -> None: ...

def getmethparlist(ob): ...
done = mainloop
