/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFrameCommand: typeof import('./src/components/AddFrameCommand.vue')['default']
    APIDiscovery: typeof import('./src/components/APIDiscovery.vue')['default']
    AutoCompletion: typeof import('./src/components/AutoCompletion.vue')['default']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    Caret: typeof import('./src/components/Caret.vue')['default']
    CaretContainer: typeof import('./src/components/CaretContainer.vue')['default']
    ChildrenFrameStateToggle: typeof import('./src/components/ChildrenFrameStateToggle.vue')['default']
    CloudDriveHandler: typeof import('./src/components/CloudDriveHandler.vue')['default']
    CloudDriveItemPicker: typeof import('./src/components/CloudDriveItemPicker.vue')['default']
    Commands: typeof import('./src/components/Commands.vue')['default']
    EditImageDlg: typeof import('./src/components/EditImageDlg.vue')['default']
    EditSoundDlg: typeof import('./src/components/EditSoundDlg.vue')['default']
    Frame: typeof import('./src/components/Frame.vue')['default']
    FrameBody: typeof import('./src/components/FrameBody.vue')['default']
    FrameContainer: typeof import('./src/components/FrameContainer.vue')['default']
    FrameHeader: typeof import('./src/components/FrameHeader.vue')['default']
    GoogleDriveComponent: typeof import('./src/components/GoogleDriveComponent.vue')['default']
    GoogleDriveFilePicker: typeof import('./src/components/GoogleDriveFilePicker.vue')['default']
    JointFrames: typeof import('./src/components/JointFrames.vue')['default']
    LabelSlot: typeof import('./src/components/LabelSlot.vue')['default']
    LabelSlotsStructure: typeof import('./src/components/LabelSlotsStructure.vue')['default']
    MediaPreviewPopup: typeof import('./src/components/MediaPreviewPopup.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MessageBanner: typeof import('./src/components/MessageBanner.vue')['default']
    ModalDlg: typeof import('./src/components/ModalDlg.vue')['default']
    OneDriveComponent: typeof import('./src/components/OneDriveComponent.vue')['default']
    OpenDemoDlg: typeof import('./src/components/OpenDemoDlg.vue')['default']
    PopUpItem: typeof import('./src/components/PopUpItem.vue')['default']
    PythonExecutionArea: typeof import('./src/components/PythonExecutionArea.vue')['default']
    SimpleMsgModalDlg: typeof import('./src/components/SimpleMsgModalDlg.vue')['default']
    SVGIcon: typeof import('./src/components/SVGIcon.vue')['default']
  }
}
