import {CaretPosition, EditorFrameObjects, Definitions, RootContainerFrameDefinition, ImportsContainerDefinition, FuncDefContainerDefinition, MainFramesContainerDefinition} from "@/types/types";

const initialState: EditorFrameObjects = {

    // "0":{"id":0,"frameType":{"type":"root","labels":[],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"","draggableGroup":"none","innerJointDraggableGroup":"none"},"isDisabled":false,"isSelected":false,"parentId":0,"childrenIds":[-1,-2,-3],"jointParentId":0,"jointFrameIds":[],"contentDict":{},"caretVisibility":"none"},"1":{"frameType":{"type":"import","labels":[{"label":"from ","slot":true,"defaultText":"module","optionalLabel":true,"toggleLabelCommand":{"type":"importFrom","modifierKeyShortcuts":["ctrl","shift"],"keyShortcut":"f","displayCommandText":"toggle from"},"optionalSlot":false},{"label":"import ","slot":true,"defaultText":"function/class","optionalSlot":false},{"label":"as ","slot":true,"defaultText":"module","optionalLabel":true,"toggleLabelCommand":{"type":"importAs","modifierKeyShortcuts":["ctrl","shift"],"keyShortcut":"a","displayCommandText":"toggle as"},"optionalSlot":false}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#CBD4C8","draggableGroup":"imports","innerJointDraggableGroup":"none"},"id":1,"isDisabled":false,"isSelected":false,"parentId":-1,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"microbit","focused":false,"error":"","shownLabel":true},"1":{"code":"*","focused":false,"error":"","shownLabel":true},"2":{"code":"","focused":false,"error":"","shownLabel":false}},"caretVisibility":"none","error":""},"2":{"frameType":{"type":"import","labels":[{"label":"from ","slot":true,"defaultText":"module","optionalLabel":true,"toggleLabelCommand":{"type":"importFrom","modifierKeyShortcuts":["ctrl","shift"],"keyShortcut":"f","displayCommandText":"toggle from"},"optionalSlot":false},{"label":"import ","slot":true,"defaultText":"function/class","optionalSlot":false},{"label":"as ","slot":true,"defaultText":"module","optionalLabel":true,"toggleLabelCommand":{"type":"importAs","modifierKeyShortcuts":["ctrl","shift"],"keyShortcut":"a","displayCommandText":"toggle as"},"optionalSlot":false}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#CBD4C8","draggableGroup":"imports","innerJointDraggableGroup":"none"},"id":2,"isDisabled":false,"isSelected":false,"parentId":-1,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"","focused":false,"error":"","shownLabel":false},"1":{"code":"music","focused":false,"error":"","shownLabel":true},"2":{"code":"","focused":false,"error":"","shownLabel":false}},"caretVisibility":"none","error":""},"5":{"frameType":{"type":"","labels":[{"label":"","slot":true,"defaultText":"method call","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":5,"isDisabled":false,"isSelected":false,"parentId":-3,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"display.scroll(\"I love Stride micro:bit !\")","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"6":{"frameType":{"type":"comment","labels":[{"label":"# ","slot":true,"defaultText":"your comment","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":6,"isDisabled":false,"isSelected":false,"parentId":-3,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"Maintain this behaviour while on:","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"7":{"frameType":{"type":"varassign","labels":[{"label":"","slot":true,"defaultText":"identifier","optionalSlot":false},{"label":" = ","slot":true,"defaultText":"value","optionalSlot":false}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":7,"isDisabled":false,"isSelected":false,"parentId":-3,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"currImg","focused":false,"error":"","shownLabel":true},"1":{"code":"Image.HEART","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"8":{"frameType":{"type":"while","labels":[{"label":"while (","slot":true,"defaultText":"condition","optionalSlot":false},{"label":") :","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#E4D5D5","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":8,"isDisabled":false,"isSelected":false,"parentId":-3,"childrenIds":[9,10,11,12],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"True","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"9":{"frameType":{"type":"","labels":[{"label":"","slot":true,"defaultText":"method call","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":9,"isDisabled":false,"isSelected":false,"parentId":8,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"display.show(currImg)","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"10":{"frameType":{"type":"varassign","labels":[{"label":"","slot":true,"defaultText":"identifier","optionalSlot":false},{"label":" = ","slot":true,"defaultText":"value","optionalSlot":false}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":10,"isDisabled":false,"isSelected":false,"parentId":8,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"gesture","focused":false,"error":"","shownLabel":true},"1":{"code":"accelerometer.current_gesture()","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"11":{"frameType":{"type":"if","labels":[{"label":"if (","slot":true,"defaultText":"condition","optionalSlot":false},{"label":") :","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":true,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally"],"isJointFrame":false,"jointFrameTypes":["elif","else"],"colour":"#E0DFE4","draggableGroup":"code","innerJointDraggableGroup":"ifCompound"},"id":11,"isDisabled":false,"isSelected":false,"parentId":8,"childrenIds":[14,15],"jointParentId":0,"jointFrameIds":[18,20],"contentDict":{"0":{"code":"gesture == \"shake\"","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"12":{"frameType":{"type":"if","labels":[{"label":"if (","slot":true,"defaultText":"condition","optionalSlot":false},{"label":") :","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":true,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally"],"isJointFrame":false,"jointFrameTypes":["elif","else"],"colour":"#E0DFE4","draggableGroup":"code","innerJointDraggableGroup":"ifCompound"},"id":12,"isDisabled":false,"isSelected":false,"parentId":8,"childrenIds":[16],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"button_a.is_pressed()","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"14":{"frameType":{"type":"","labels":[{"label":"","slot":true,"defaultText":"method call","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":14,"isDisabled":false,"isSelected":false,"parentId":11,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"display.show(Image.SAD)","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"15":{"frameType":{"type":"","labels":[{"label":"","slot":true,"defaultText":"method call","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":15,"isDisabled":false,"isSelected":false,"parentId":11,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"sleep(2000)","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"16":{"frameType":{"type":"varassign","labels":[{"label":"","slot":true,"defaultText":"identifier","optionalSlot":false},{"label":" = ","slot":true,"defaultText":"value","optionalSlot":false}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":16,"isDisabled":false,"isSelected":false,"parentId":12,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{"0":{"code":"currImg","focused":false,"error":"","shownLabel":true},"1":{"code":"Image.CHESSBOARD","focused":false,"error":"","shownLabel":true}},"caretVisibility":"none","error":""},"18":{"frameType":{"type":"elif","labels":[{"label":"elif (","slot":true,"defaultText":"condition","optionalSlot":false},{"label":") :","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally"],"isJointFrame":true,"jointFrameTypes":["elif","else"],"colour":"","draggableGroup":"ifCompound","innerJointDraggableGroup":"none"},"id":18,"isDisabled":false,"isSelected":false,"parentId":0,"childrenIds":[19],"jointParentId":11,"jointFrameIds":[],"caretVisibility":"none","contentDict":{"0":{"code":"true","focused":false,"error":"","shownLabel":true}},"error":""},"19":{"frameType":{"type":"","labels":[{"label":"","slot":true,"defaultText":"method call","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":19,"isDisabled":false,"isSelected":false,"parentId":18,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"caretVisibility":"none","contentDict":{"0":{"code":"f","focused":false,"error":"","shownLabel":true}},"error":""},"20":{"frameType":{"type":"else","labels":[{"label":"else:","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally"],"isJointFrame":true,"jointFrameTypes":["finally"],"colour":"","draggableGroup":"ifCompound","innerJointDraggableGroup":"none"},"id":20,"isDisabled":false,"isSelected":false,"parentId":0,"childrenIds":[21],"jointParentId":11,"jointFrameIds":[],"caretVisibility":"none","contentDict":{},"error":""},"21":{"frameType":{"type":"","labels":[{"label":"","slot":true,"defaultText":"method call","optionalSlot":true}],"allowChildren":false,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","comment","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#F6F2E9","draggableGroup":"code","innerJointDraggableGroup":"none"},"id":21,"isDisabled":false,"isSelected":false,"parentId":20,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"caretVisibility":"none","contentDict":{"0":{"code":"a","focused":false,"error":"","shownLabel":true}},"error":""},"-1":{"id":-1,"frameType":{"type":"importsContainer","labels":[{"label":"Imports:","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["funcdef","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#BBC6B6","draggableGroup":"imports","innerJointDraggableGroup":"none"},"isDisabled":false,"isSelected":false,"parentId":0,"childrenIds":[1,2],"jointParentId":0,"jointFrameIds":[],"contentDict":{},"caretVisibility":"none"},"-2":{"id":-2,"frameType":{"type":"funcDefsContainer","labels":[{"label":"Function Definitions:","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["import","","if","for","while","break","continue","try","raise","with","return","varassign","elif","else","except","finally"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#BBC6B6","draggableGroup":"functionSignatures","innerJointDraggableGroup":"none"},"isDisabled":false,"isSelected":false,"parentId":0,"childrenIds":[],"jointParentId":0,"jointFrameIds":[],"contentDict":{},"caretVisibility":"none"},"-3":{"id":-3,"frameType":{"type":"funcDefsContainer","labels":[{"label":"Your code:","slot":false,"defaultText":""}],"allowChildren":true,"allowJointChildren":false,"forbiddenChildrenTypes":["import","funcdef","else","elif","except","finally","import","funcdef"],"isJointFrame":false,"jointFrameTypes":[],"colour":"#BBC6B6","draggableGroup":"code","innerJointDraggableGroup":"none"},"isDisabled":false,"isSelected":false,"parentId":0,"childrenIds":[5,6,7,8],"jointParentId":0,"jointFrameIds":[],"contentDict":{},"caretVisibility":"none"},
    0: {
        id: 0,
        frameType : RootContainerFrameDefinition,
        isDisabled: false,
        isSelected: false,
        parentId: 0,
        childrenIds: [-1, -2, -3],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { },
        caretVisibility: CaretPosition.none,
    },
    "-1": {
        id: -1,
        frameType : ImportsContainerDefinition,
        isDisabled: false,
        isSelected: false,
        parentId: 0,
        childrenIds: [1,2],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    "-2": {
        id: -2,
        frameType : FuncDefContainerDefinition,
        isDisabled: false,
        isSelected: false,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { },
        caretVisibility: CaretPosition.none,
    },
    "-3": {
        id: -3,
        frameType : MainFramesContainerDefinition,
        isDisabled: false,
        isSelected: false,
        parentId: 0,
        childrenIds: [3,4,5,6,7,8],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.body,
    },
    1: {
        frameType: Definitions.ImportDefinition,
        id: 1,
        isDisabled: false,
        isSelected: false,
        parentId: -1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code : "microbit", focused: false, error :"", shownLabel: true},
            1: {code : "*", focused: false, error :"", shownLabel: true},
            2: {code : "", focused: false, error :"", shownLabel: false} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    2: {
        frameType: Definitions.ImportDefinition,
        id: 2,
        isDisabled: false,
        isSelected: false,
        parentId: -1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code : "", focused: false, error :"", shownLabel: false},
            1: {code : "music", focused: false, error :"", shownLabel: true},
            2: {code : "", focused: false, error :"", shownLabel: false} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    3: {
        frameType: Definitions.CommentDefinition,
        id: 3,
        isDisabled: false,
        isSelected: false,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "At start:", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    4: {
        frameType: Definitions.EmptyDefinition,
        id: 4,
        isDisabled: false,
        isSelected: false,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "music.play(music.NYAN)", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    5: {
        frameType: Definitions.EmptyDefinition,
        id: 5,
        isDisabled: false,
        isSelected: false,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "display.scroll(\"I love Stride micro:bit !\")", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    6: {
        frameType: Definitions.CommentDefinition,
        id: 6,
        isDisabled: false,
        isSelected: false,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "Maintain this behaviour while on:", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    7: {
        frameType: Definitions.VarAssignDefinition,
        id: 7,
        isDisabled: false,
        isSelected: false,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "currImg", focused: false, error :"", shownLabel: true},
            1: {code :  "Image.HEART", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    8: {
        frameType: Definitions.WhileDefinition,
        id: 8,
        isDisabled: false,
        isSelected: false,
        parentId: -3,
        childrenIds: [9,10,11,12,13],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {0: {code :  "True", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    9: {
        frameType: Definitions.EmptyDefinition,
        id: 9,
        isDisabled: false,
        isSelected: false,
        parentId: 8,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "display.show(currImg)", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    10: {
        frameType: Definitions.VarAssignDefinition,
        id: 10,
        isDisabled: false,
        isSelected: false,
        parentId: 8,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "gesture", focused: false, error :"", shownLabel: true},
            1: {code :  "accelerometer.current_gesture()", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    11: {
        frameType: Definitions.IfDefinition,
        id: 11,
        isDisabled: false,
        isSelected: false,
        parentId: 8,
        childrenIds: [14,15],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "gesture == \"shake\"", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    14: {
        frameType: Definitions.EmptyDefinition,
        id: 14,
        isDisabled: false,
        isSelected: false,
        parentId: 11,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "display.show(Image.SAD)", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    15: {
        frameType: Definitions.EmptyDefinition,
        id: 15,
        isDisabled: false,
        isSelected: false,
        parentId: 11,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "sleep(2000)", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    12: {
        frameType: Definitions.IfDefinition,
        id: 12,
        isDisabled: false,
        isSelected: false,
        parentId: 8,
        childrenIds: [16],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "button_a.is_pressed()", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    16: {
        frameType: Definitions.VarAssignDefinition,
        id: 16,
        isDisabled: false,
        isSelected: false,
        parentId: 12,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "currImg", focused: false, error :"", shownLabel: true},
            1: {code :  "Image.CHESSBOARD", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    13: {
        frameType: Definitions.IfDefinition,
        id: 13,
        isDisabled: false,
        isSelected: false,
        parentId: 8,
        childrenIds: [17],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "button_b.is_pressed()", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
    17: {
        frameType: Definitions.VarAssignDefinition,
        id: 17,
        isDisabled: false,
        isSelected: false,
        parentId: 13,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "currImg", focused: false, error :"", shownLabel: true},
            1: {code :  "Image.COW", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
    },
};

export default initialState;
