import { FrameObject, CaretPosition, RootContainerFrameDefinition, IfDefinition, ElseDefinition, ForDefinition, WhileDefinition, ImportsContainerDefinition, FuncDefContainerDefinition, MainFramesContainerDefinition, ReturnDefinition } from "@/types/types";

const initialState: { [id: number]: FrameObject } = {
    0: {
        id: 0,
        frameType : RootContainerFrameDefinition,
        parentId: 0,
        childrenIds: [-1, -2, -3],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.body,
    },
    "-1": {
        id: -1,
        frameType : ImportsContainerDefinition,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    "-2": {
        id: -2,
        frameType : FuncDefContainerDefinition,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    "-3": {
        id: -3,
        frameType : MainFramesContainerDefinition,
        parentId: 0,
        childrenIds: [1,3],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    1: {
        id: 1,
        frameType : IfDefinition,
        parentId: -3,
        childrenIds: [4,5],
        jointParentId: 0,
        jointFrameIds: [2],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    2: {
        id: 2,
        frameType : ElseDefinition,
        parentId: 0,
        childrenIds: [],
        jointParentId: 1,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    3: {
        id: 3,
        frameType : ForDefinition,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    4: {
        id: 4,
        frameType : WhileDefinition,
        parentId: 1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    5: {
        id: 5,
        frameType : ReturnDefinition,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },

};

export default initialState;
