import {CaretPosition, EditorFrameObjects, Definitions, RootContainerFrameDefinition, ImportsContainerDefinition, FuncDefContainerDefinition, MainFramesContainerDefinition} from "@/types/types";

const initialDemoState: EditorFrameObjects = {
    0: {
        id: 0,
        frameType : RootContainerFrameDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [-1, -2, -3],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    "-1": {
        id: -1,
        frameType : ImportsContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [1],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    "-2": {
        id: -2,
        frameType : FuncDefContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    "-3": {
        id: -3,
        frameType : MainFramesContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [2,3],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.body,
        multiDragPosition: "",
    },

    1: {
        frameType: Definitions.FromImportDefinition,
        id: 1,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code : "microbit", focused: false, error :"", shownLabel: true},
            1: {code : "*", focused: false, error :"", shownLabel: true},
            2: {code : "", focused: false, error :"", shownLabel: false} },
        caretVisibility: CaretPosition.none,
        error: "",
        multiDragPosition: "",
    },

    2: {
        frameType: Definitions.VarAssignDefinition,
        id: 2,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "myString", focused: false, error :"", shownLabel: true},
            1: {code :  "\"Hello micro:bit!\"", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        error: "",
        multiDragPosition: "",
    },

    3: {
        frameType: Definitions.WhileDefinition,
        id: 3,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -3,
        childrenIds: [4],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "True", focused: false, error :"", shownLabel: true},
        },
        caretVisibility: CaretPosition.none,
        error: "",
        multiDragPosition: "",
    },

    4: {
        frameType: Definitions.EmptyDefinition,
        id: 4,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {
            0: {code :  "display.scroll(myString)", focused: false, error :"", shownLabel: true},
        },
        caretVisibility: CaretPosition.none,
        error: "",
        multiDragPosition: "",
    },

};

export default initialDemoState;


