import { EditorFrameObjects, CaretPosition } from "@/types/types";

const initialState: EditorFrameObjects = {
    0: {
        id: 0,
        parentId: -1,
        childrenIds: [1, 2, 3],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: {},
        caretVisibility: CaretPosition.none,
    },
    1: {
        frameType: {
            type: "comment",
            labels: [{ label: "Comment:", slot: true }],
            allowChildren: false,
            jointFrameTypes: [],
            colour: "#AAAAAA",
        },
        id: 1,
        parentId: 0,
        childrenIds: [],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: { 0: "Add your Python code here. E.g." },
        caretVisibility: CaretPosition.none,
    },
    2: {
        frameType: {
            type: "fromimport",
            labels: [
                { label: "from", slot: true },
                { label: "import", slot: true },
            ],
            allowChildren: false,
            jointFrameTypes: [],
            colour: "#FFFFFF",
        },
        id: 2,
        parentId: 0,
        childrenIds: [],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: { 0: "microbit", 1: "*" },
        caretVisibility: CaretPosition.none,
    },
    3: {
        frameType: {
            type: "while",
            labels: [
                { label: "while", slot: true },
                { label: ":", slot: false },
            ],
            allowChildren: true,
            jointFrameTypes: [],
            colour: "#9C72EA",
        },
        id: 3,
        parentId: 0,
        childrenIds: [4, 5, 6],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: { 0: "True" },
        caretVisibility: CaretPosition.none,
    },
    4: {
        frameType: {
            type: "empty",
            labels: [{ label: "", slot: true }],
            allowChildren: false,
            jointFrameTypes: [],
            colour: "#FFFFFF",
        },
        id: 4,
        parentId: 3,
        childrenIds: [],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: {0: "display.scroll('Hello, World!')"},
        caretVisibility: CaretPosition.none,
    },
    5: {
        frameType: {
            type: "empty",
            labels: [{ label: "", slot: true }],
            allowChildren: false,
            jointFrameTypes: [],
            colour: "#FFFFFF",
        },
        id: 5,
        parentId: 3,
        childrenIds: [],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: {0: "display.show(Image.HEART)"},
        caretVisibility: CaretPosition.none,
    },
    6: {
        frameType: {
            type: "empty",
            labels: [{ label: "", slot: true }],
            allowChildren: false,
            jointFrameTypes: [],
            colour: "#FFFFFF",
        },
        id: 6,
        parentId: 3,
        childrenIds: [],
        jointParentId: -1,
        jointFrameIds: [],
        contentDict: {0: "sleep(2000)"},
        caretVisibility: CaretPosition.none,
    },
};

export default initialState;
