export const pythonBuiltins : Record<string, { type: "module", documentation?: string, version: 0 }> = 
{
    // The modules are manually inferred from Skulpt https://github.com/skulpt/skulpt/tree/master/src/lib
    // Anything that appears to be implemented is listed here:
    "test": {type: "module", documentation: "Regression tests package for Python.", version: 0},
    "unittest": {type: "module", documentation: "Unit testing framework.", version: 0},
    "urllib": {type: "module", documentation: "URL handling modules.", version: 0},
    "urllib.request": {type: "module", documentation: "Extensible library for opening URLs.", version: 0},
    "webgl": {type: "module", version: 0},
    "antigravity": {type: "module", version: 0},
    "array": {type: "module", documentation: "Efficient arrays of numeric values.", version: 0},
    "bisect": {type: "module", documentation: "Array bisection algorithm.", version: 0},
    "collections": {type: "module", documentation: "Container datatypes.", version: 0},
    "copy": {type: "module", documentation: "Shallow and deep copy operations.", version: 0},
    "datetime": {type: "module", documentation: "Basic date and time types.", version: 0},
    "document": {type: "module", version: 0},
    "image": {type: "module", version: 0},
    "itertools": {type: "module", documentation: "Functions creating iterators for efficient looping.", version: 0},
    "keyword": {type: "module", documentation: "Testing for Python keywords.", version: 0},
    "math": {type: "module", documentation: "Mathematical functions.", version: 0},
    "numbers": {type: "module", documentation: "Numeric abstract base classes.", version: 0},
    "operator": {type: "module", documentation: "Standard operators as functions.", version: 0},
    "platform": {type: "module", documentation: "Access to underlying platform’s identifying data.", version: 0},
    "processing": {type: "module", version: 0},
    "random": {type: "module", documentation: "Generate pseudo-random numbers.", version: 0},
    "re": {type: "module", documentation: "Regular expression operations.", version: 0},
    "signal": {type: "module", documentation: "Set handlers for asynchronous events.", version: 0},
    "string": {type: "module", documentation: "Common string operations.", version: 0},
    "textwrap": {type: "module", documentation: "Text wrapping and filling.", version: 0},
    "time": {type: "module", documentation: "Time access and conversions.", version: 0},
    "token": {type: "module", documentation: "Constants used with Python parse trees.", version: 0},
    "tokenize": {type: "module", documentation: "Tokenizer for Python source.", version: 0},
    "types": {type: "module", documentation: "Dynamic type creation and names for built-in types.", version: 0},
    "webbrowser": {type: "module", documentation: "Convenient web-browser controller.", version: 0},
    "turtle": {type: "module", documentation: "Implementation of the Turtle graphics.", version: 0},
};
