import {CaretPosition, EditorFrameObjects, RootContainerFrameDefinition, ImportsContainerDefinition, FuncDefContainerDefinition, MainFramesContainerDefinition, getFrameDefType, AllFrameTypesIdentifier} from "@/types/types";

const initialTestState: EditorFrameObjects = {
    0: {
        id: 0,
        frameType : RootContainerFrameDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [-1, -2, -3],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    "-1": {
        id: -1,
        frameType : ImportsContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        isCollapsed: false,
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    "-2": {
        id: -2,
        frameType : FuncDefContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { },
        isCollapsed: false,
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    "-3": {
        id: -3,
        frameType : MainFramesContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [1,5,6,7],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: {},
        isCollapsed: false,
        caretVisibility: CaretPosition.body,
        multiDragPosition: "",
    },

    1: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.if),
        id: 1,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -3,
        childrenIds: [2],
        jointParentId: 0,
        jointFrameIds: [3],
        contentDict: { 0: {code :  "1 > 0", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },

    2: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.empty),
        id: 2,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "a = 2", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    3: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.elif),
        id: 3,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [4],
        jointParentId: 1,
        jointFrameIds: [],
        contentDict: { 0: {code :  "3", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    4: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.empty),
        id: 4,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "a = 4", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    5: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.empty),
        id: 5,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "print(5)", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    6: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.empty),
        id: 6,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "x = 6", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
    7: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.empty),
        id: 7,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -3,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        contentDict: { 0: {code :  "a = 7", focused: false, error :"", shownLabel: true} },
        caretVisibility: CaretPosition.none,
        multiDragPosition: "",
    },
   


};

export default initialTestState;


